In [1]:
import pandas as pd

In [2]:
# Load the Excel file to inspect sheet names
file_path = '(반출)홈페이지_공시실_상품공시_전체상품_20240913.xlsx'

In [3]:
# Load Excel file to inspect sheet names
xls = pd.ExcelFile(file_path)
xls.sheet_names

['1. 판매중', '2. 판매중지']

In [4]:
# Load the specified sheets "1. 판매중" and "2. 판매중지"
df_selling = pd.read_excel(file_path, sheet_name='1. 판매중')
df_discontinued = pd.read_excel(file_path, sheet_name='2. 판매중지')

# Preview a few rows to inspect the structure and locate columns for meta data
df_selling.head(), df_discontinued.head()

(   Unnamed: 0  Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
 0         NaN         NaN     META01     META02     META03     META04
 1         NaN         1.0      신한라이프         TM         보장    7000273
 2         NaN         2.0      신한라이프         TM         보장    7000216
 3         NaN         3.0      신한라이프         TM         보장    7000216
 4         NaN         4.0      신한라이프         TM         보장        NaN

                                Unnamed: 6 Unnamed: 7      Unnamed: 8  \
 0                                  META05     META06          META07
 1  (간편)신한통합건강보장보험 원(ONE)(무배당, 해약환급금 미지급형)       TRUE  20240903000000
 2  (간편)신한통합건강보장보험 원(ONE)(무배당, 해약환급금 미지급형)       TRUE  20240701000000
 3  (간편)신한통합건강보장보험 원(ONE)(무배당, 해약환급금 미지급형)       TRUE  20240610000000
 4  (간편)신한통합건강보장보험 원(ONE)(무배당, 해약환급금 미지급형)       TRUE  20240503000000

        Unnamed: 9 Unnamed: 10  \
 0          META08      META09
 1  99991231000000         NaN
 2  20240902000000         NaN
 3  20240630000000         NaN
 4  20240609000000         NaN

                                          Unnamed: 11  \
 0                                             META10
 1  /repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/01...
 2  /repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/01...
 3  /repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/사업...
 4  /repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/사업...

                                          Unnamed: 12 Unnamed: 13
 0                                             META11      META13
 1  /repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/판매...         NaN
 2  /repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/SH...         NaN
 3  /repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/판매...         NaN
 4  /repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/약관...         NaN  ,
    Unnamed: 0  Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
 0         NaN         NaN     META01     META02     META03     META04
 1         NaN         1.0    (구)신한생명         CM         보장        NaN
 2         NaN         2.0    (구)신한생명         CM         보장        NaN
 3         NaN         3.0    (구)신한생명         CM         보장        NaN
 4         NaN         4.0    (구)신한생명         CM         보장        NaN

                    Unnamed: 6 Unnamed: 7      Unnamed: 8      Unnamed: 9  \
 0                      META05     META06          META07          META08
 1  (무)Birth Start Travel 선물보험      FALSE  20210101000000  20210630000000
 2  (무)Birth Start Travel 선물보험      FALSE  20200813000000  20201231000000
 3     (무)VVIP더블플러스종신보험Premium      FALSE  20150101000000  20150331000000
 4     (무)VVIP더블플러스종신보험Premium      FALSE  20141001000000  20141231000000

   Unnamed: 10                                        Unnamed: 11  \
 0      META09                                             META10
 1         NaN  /repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/사업...
 2         NaN  /repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/사업...
 3         NaN  /repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/(무...
 4         NaN  /repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/(무...

                                          Unnamed: 12 Unnamed: 13 Unnamed: 14  \
 0                                             META11      META13      META14
 1  /repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/판매...         NaN         352
 2  /repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/판매...         NaN         352
 3  /repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/(무...         NaN         352
 4  /repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/(무...         NaN         352

   Unnamed: 15 Unnamed: 16
 0      META15        PAGE
 1           2           1
 2           2           1
 3           4           1
 4           4           1  )

In [9]:
# Adjusting the column selection to correctly match the available data
# We'll use columns C2 to L2 based on the structure previewed earlier

columns_meta_adjusted = ['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 
                         'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 
                         'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

# Filter the metadata from both dataframes
df_selling_filtered = df_selling[columns_meta_adjusted]
df_discontinued_filtered = df_discontinued[columns_meta_adjusted]

# Add a new column to identify the source sheet
df_selling_filtered['Source'] = '판매중'
df_discontinued_filtered['Source'] = '판매중지'

# Merge both sheets into one dataframe
df_combined = pd.concat([df_selling_filtered, df_discontinued_filtered], ignore_index=True)

# Rename the columns according to the metadata headers (META01 to META12)
meta_headers_adjusted = ['META01', 'META02', 'META03', 'META04', 'META05', 'META06', 'META07', 
                         'META08', 'META09', 'META10', 'META11', 'META12', 'Source']
df_combined.columns = meta_headers_adjusted

# Add a "순번" column with sequential numbering starting from 1
df_combined.insert(0, '순번', range(1, len(df_combined) + 1))

# Remove the second row (which contains metadata labels)
df_combined_cleaned = df_combined.drop(0).reset_index(drop=True)

# Since "순번" already exists, we can update it rather than inserting it again
df_combined_cleaned['순번'] = range(1, len(df_combined_cleaned) + 1)

df_combined_cleaned

/tmp/ipykernel_156/438444206.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selling_filtered['Source'] = '판매중'
/tmp/ipykernel_156/438444206.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_discontinued_filtered['Source'] = '판매중지'

,순번,META01,META02,META03,META04,META05,META06,META07,META08,META09,META10,META11,META12,Source
0,1,신한라이프,TM,보장,7000273,"(간편)신한통합건강보장보험 원(ONE)(무배당, 해약환급금 미지급형)",TRUE,20240903000000,99991231000000,NaN,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/01...,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/판매...,NaN,판매중
1,2,신한라이프,TM,보장,7000216,"(간편)신한통합건강보장보험 원(ONE)(무배당, 해약환급금 미지급형)",TRUE,20240701000000,20240902000000,NaN,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/01...,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/SH...,NaN,판매중
2,3,신한라이프,TM,보장,7000216,"(간편)신한통합건강보장보험 원(ONE)(무배당, 해약환급금 미지급형)",TRUE,20240610000000,20240630000000,NaN,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/사업...,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/판매...,NaN,판매중
3,4,신한라이프,TM,보장,NaN,"(간편)신한통합건강보장보험 원(ONE)(무배당, 해약환급금 미지급형)",TRUE,20240503000000,20240609000000,NaN,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/사업...,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/약관...,NaN,판매중
4,5,NaN,TM,보장,NaN,"(간편)신한통합건강보장보험 원(ONE)(무배당, 해약환급금 미지급형)",TRUE,20240401140454,20240502000000,NaN,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/사업...,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/판매...,NaN,판매중
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7485,7486,(구)오렌지라이프,특약(2002년이전),보장,NaN,정기특약,FALSE,19970401000000,20000331000000,NaN,NaN,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/P_...,NaN,판매중지
7486,7487,(구)오렌지라이프,특약(2002년이전),보장,NaN,정기특약,FALSE,19951102000000,19970331000000,NaN,NaN,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/P_...,NaN,판매중지
7487,7488,(구)오렌지라이프,특약(2002년이전),보장,NaN,체감정기특약,FALSE,20000401000000,20010701000000,NaN,NaN,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/20...,NaN,판매중지
7488,7489,(구)오렌지라이프,특약(2002년이전),보장,NaN,체감정기특약,FALSE,19970401000000,20000331000000,NaN,NaN,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/P_...,NaN,판매중지
7489,7490,(구)오렌지라이프,특약(2002년이전),보장,NaN,체감정기특약,FALSE,19951102000000,19970331000000,NaN,NaN,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/P_...,NaN,판매중지

In [10]:
# We will create a new DataFrame where each "순번" will be expanded to multiple rows 
# (one for each of META09, META10, META11, META12), and we will add a "출처" column.

# Define the META columns that will be reshaped
meta_columns = ['META09', 'META10', 'META11', 'META12']

# We will collect the expanded rows in a list to create the new DataFrame
expanded_rows = []

# Iterate through each row in the cleaned dataframe
for index, row in df_combined_cleaned.iterrows():
    for meta_col in meta_columns:
        # Create a new row with the same data as the original row, but with the value from one of the META columns
        new_row = row.copy()
        new_row['출처'] = meta_col
        new_row['파일경로'] = new_row[meta_col]
        expanded_rows.append(new_row)

# Create a new DataFrame from the expanded rows
df_expanded = pd.DataFrame(expanded_rows)

# Drop the original META09, META10, META11, META12 columns as they are now redundant
df_expanded.drop(columns=meta_columns, inplace=True)

df_expanded

,순번,META01,META02,META03,META04,META05,META06,META07,META08,Source,출처,파일경로
0,1,신한라이프,TM,보장,7000273,"(간편)신한통합건강보장보험 원(ONE)(무배당, 해약환급금 미지급형)",TRUE,20240903000000,99991231000000,판매중,META09,NaN
0,1,신한라이프,TM,보장,7000273,"(간편)신한통합건강보장보험 원(ONE)(무배당, 해약환급금 미지급형)",TRUE,20240903000000,99991231000000,판매중,META10,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/01...
0,1,신한라이프,TM,보장,7000273,"(간편)신한통합건강보장보험 원(ONE)(무배당, 해약환급금 미지급형)",TRUE,20240903000000,99991231000000,판매중,META11,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/판매...
0,1,신한라이프,TM,보장,7000273,"(간편)신한통합건강보장보험 원(ONE)(무배당, 해약환급금 미지급형)",TRUE,20240903000000,99991231000000,판매중,META12,NaN
1,2,신한라이프,TM,보장,7000216,"(간편)신한통합건강보장보험 원(ONE)(무배당, 해약환급금 미지급형)",TRUE,20240701000000,20240902000000,판매중,META09,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
7488,7489,(구)오렌지라이프,특약(2002년이전),보장,NaN,체감정기특약,FALSE,19970401000000,20000331000000,판매중지,META12,NaN
7489,7490,(구)오렌지라이프,특약(2002년이전),보장,NaN,체감정기특약,FALSE,19951102000000,19970331000000,판매중지,META09,NaN
7489,7490,(구)오렌지라이프,특약(2002년이전),보장,NaN,체감정기특약,FALSE,19951102000000,19970331000000,판매중지,META10,NaN
7489,7490,(구)오렌지라이프,특약(2002년이전),보장,NaN,체감정기특약,FALSE,19951102000000,19970331000000,판매중지,META11,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/P_...
7489,7490,(구)오렌지라이프,특약(2002년이전),보장,NaN,체감정기특약,FALSE,19951102000000,19970331000000,판매중지,META12,NaN

In [11]:
# Adjust the code to update the column name from '출처' to '상품내역유형'
# and replace the values in this column using the type_mapping

# Define the mapping for '상품내역유형'
type_mapping = {
    'META09': '상품요약서',
    'META10': '사업방법서',
    'META11': '판매약관',
    'META12': '상품특약'
}

# Replace '출처' with '상품내역유형' and apply the type_mapping
df_expanded['상품내역유형'] = df_expanded['출처'].map(type_mapping)

# Drop the old '출처' column as it's no longer needed
df_expanded.drop(columns=['출처'], inplace=True)

df_expanded

,순번,META01,META02,META03,META04,META05,META06,META07,META08,Source,파일경로,상품내역유형
0,1,신한라이프,TM,보장,7000273,"(간편)신한통합건강보장보험 원(ONE)(무배당, 해약환급금 미지급형)",TRUE,20240903000000,99991231000000,판매중,NaN,상품요약서
0,1,신한라이프,TM,보장,7000273,"(간편)신한통합건강보장보험 원(ONE)(무배당, 해약환급금 미지급형)",TRUE,20240903000000,99991231000000,판매중,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/01...,사업방법서
0,1,신한라이프,TM,보장,7000273,"(간편)신한통합건강보장보험 원(ONE)(무배당, 해약환급금 미지급형)",TRUE,20240903000000,99991231000000,판매중,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/판매...,판매약관
0,1,신한라이프,TM,보장,7000273,"(간편)신한통합건강보장보험 원(ONE)(무배당, 해약환급금 미지급형)",TRUE,20240903000000,99991231000000,판매중,NaN,상품특약
1,2,신한라이프,TM,보장,7000216,"(간편)신한통합건강보장보험 원(ONE)(무배당, 해약환급금 미지급형)",TRUE,20240701000000,20240902000000,판매중,NaN,상품요약서
...,...,...,...,...,...,...,...,...,...,...,...,...
7488,7489,(구)오렌지라이프,특약(2002년이전),보장,NaN,체감정기특약,FALSE,19970401000000,20000331000000,판매중지,NaN,상품특약
7489,7490,(구)오렌지라이프,특약(2002년이전),보장,NaN,체감정기특약,FALSE,19951102000000,19970331000000,판매중지,NaN,상품요약서
7489,7490,(구)오렌지라이프,특약(2002년이전),보장,NaN,체감정기특약,FALSE,19951102000000,19970331000000,판매중지,NaN,사업방법서
7489,7490,(구)오렌지라이프,특약(2002년이전),보장,NaN,체감정기특약,FALSE,19951102000000,19970331000000,판매중지,/repo/DigitalPlattform/cdh/cdhi/gd/pr/__etc/P_...,판매약관
7489,7490,(구)오렌지라이프,특약(2002년이전),보장,NaN,체감정기특약,FALSE,19951102000000,19970331000000,판매중지,NaN,상품특약

In [6]:
# Save the merged dataframe to a new Excel file using openpyxl
output_file_path = '통합상품_병합.xlsx'

# Use openpyxl as the engine
with pd.ExcelWriter(output_file_path, engine='openpyxl') as writer:
    df_expanded.to_excel(writer, sheet_name='통합상품', index=False)

output_file_path

'통합상품_병합.xlsx'